# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-11386-nagaoka-lab/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a200tsbg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/ec67/hdl
    /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/85a3
  } {
      /opt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/ec67/hdl
    /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/85a3
  } {
      ./.Xil/Vivado-11386-nagaoka-lab/realtime/rgb2dvi_0_stub.v
      ./.Xil/Vivado-11386-nagaoka-lab/realtime/vram_stub.v
      ./.Xil/Vivado-11386-nagaoka-lab/realtime/clk_hdmi_top_stub.v
      ./.Xil/Vivado-11386-nagaoka-lab/realtime/clocking_stub.v
      ./.Xil/Vivado-11386-nagaoka-lab/realtime/bram_compare_stub.v
      ./.Xil/Vivado-11386-nagaoka-lab/realtime/fifo_9w16d_stub.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/cc23/hdl/axi_register_slice_v2_1_vl_rfs.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/c4fd/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/6c9d/hdl/axi_crossbar_v2_1_vl_rfs.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_xbar_0/synth/design_2_xbar_0.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_microblaze_0_xlconcat_0/synth/design_2_microblaze_0_xlconcat_0.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0_clk_wiz.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/synth/design_2.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/bram2rgb.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/cnv8to24.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/comparator.v
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/hdl/design_2_wrapper.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/detect_errors2.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/ext_crc.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/ext_preamble.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/five2one_v2.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/hdmi_top.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/n2one.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/one2one.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/rgmii_rx.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/rx_majority_wrapper.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/three2one_v2.v
      /home/nagaoka/Dropbox/vivado_source/rx_rtl_files/rx_top.v
    }
      rt::read_vhdl -lib microblaze_v11_0_0 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/2ed1/hdl/microblaze_v11_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_microblaze_0_0/synth/design_2_microblaze_0_0.vhd
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_dlmb_v10_0/synth/design_2_dlmb_v10_0.vhd
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_ilmb_v10_0/synth/design_2_ilmb_v10_0.vhd
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_dlmb_bram_if_cntlr_0/synth/design_2_dlmb_bram_if_cntlr_0.vhd
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_ilmb_bram_if_cntlr_0/synth/design_2_ilmb_bram_if_cntlr_0.vhd
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_lmb_bram_0/synth/design_2_lmb_bram_0.vhd
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_mdm_1_0/synth/design_2_mdm_1_0.vhd
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_1_100M_0/synth/design_2_rst_clk_wiz_1_100M_0.vhd
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/synth/design_2_axi_uartlite_0_0.vhd
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/synth/design_2_axi_gpio_0_0.vhd
      /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ip/design_2_axi_intc_0_1/synth/design_2_axi_intc_0_1.vhd
    }
      rt::read_vhdl -lib lmb_v10_v3_0_9 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/78eb/hdl/lmb_v10_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lmb_bram_if_cntlr_v4_0_15 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/92fd/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_2 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/37c2/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_3 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/64f4/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mdm_v3_2_15 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/41ef/hdl/mdm_v3_2_vh_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_2 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_2 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_uartlite_v2_0_22 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/7371/hdl/axi_uartlite_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_20 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/a7c9/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_intc_v4_1_12 /home/nagaoka/1_working/rx_3.3/rx_3.3.srcs/sources_1/bd/design_2/ipshared/31e4/hdl/axi_intc_v4_1_vh_rfs.vhd
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top rx_top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-11386-nagaoka-lab/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
